services:
  - type: web
    name: helpdesk-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CRM.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CRM.settings
      - key: SECRET_KEY
        value: secretkey
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk-db
          property: connectionString

databases:
  - name: helpdesk-db
